const countryData = [
    { code: 'US', value: 'United States 🇺🇸' },
    { code: 'CA', value: 'Canada 🇨🇦' },
    { code: 'GB', value: 'United Kingdom 🇬🇧' },
    { code: 'AU', value: 'Australia 🇦🇺' },
    { code: 'NZ', value: 'New Zealand 🇳🇿' },
    { code: 'JP', value: 'Japan 🇯🇵' },
    { code: 'CN', value: 'China 🇨🇳' },
    { code: 'KR', value: 'South Korea 🇰🇷' },
    { code: 'SG', value: 'Singapore 🇸🇬' },
    { code: 'MY', value: 'Malaysia 🇲🇾' },
    { code: 'ID', value: 'Indonesia 🇮🇩' },
    { code: 'TH', value: 'Thailand 🇹🇭' },
    { code: 'IN', value: 'India 🇮🇳' },
    { code: 'MX', value: 'Mexico 🇲🇽' },
    { code: 'BR', value: 'Brazil 🇧🇷' },
    { code: 'AR', value: 'Argentina 🇦🇷' },
    { code: 'ZA', value: 'South Africa 🇿🇦' },
    { code: 'NG', value: 'Nigeria 🇳🇬' },
    { code: 'EG', value: 'Egypt 🇪🇬' },
    { code: 'SA', value: 'Saudi Arabia 🇸🇦' },
    { code: 'AE', value: 'United Arab Emirates 🇦🇪' },
    { code: 'TR', value: 'Turkey 🇹🇷' },
    { code: 'DE', value: 'Germany 🇩🇪' },
    { code: 'FR', value: 'France 🇫🇷' },
    { code: 'IT', value: 'Italy 🇮🇹' },
    { code: 'ES', value: 'Spain 🇪🇸' },
    { code: 'PT', value: 'Portugal 🇵🇹' },
    { code: 'NL', value: 'Netherlands 🇳🇱' },
    { code: 'SE', value: 'Sweden 🇸🇪' },
    { code: 'NO', value: 'Norway 🇳🇴' },
    { code: 'FI', value: 'Finland 🇫🇮' },
    { code: 'DK', value: 'Denmark 🇩🇰' },
    { code: 'CH', value: 'Switzerland 🇨🇭' },
    { code: 'AT', value: 'Austria 🇦🇹' },
  ];

export default countryData;  